insert into todo(ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE)
values(10001,'in28minutes','Get AWS CERTIFIED',CURRENT_DATE(),false);

insert into todo(ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE)
values(10002,'in28minutes','Get AWS CERTIFIED 1',CURRENT_DATE(),false);

insert into todo(ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE)
values(10003,'in28minutes','Get AWS CERTIFIED 2',CURRENT_DATE(),false);

insert into todo(ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE)
values(10004,'in28minutes','Get AWS CERTIFIED 3',CURRENT_DATE(),false);

insert into todo(ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE)
values(10005,'in28minutes','Get AWS CERTIFIED 4',CURRENT_DATE(),false);